name: 'On new products-improvement issue action'
description: 'Add multiple property to the issue'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The repo'
    required: true
  issue_number:
    description: 'The number of the issue'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
